"""baseline schema

Captures the schema exactly as produced by the pre-Alembic hand-rolled migration
path in app/db.py (_rename_legacy_tables_and_columns, create_all,
_add_missing_columns, _backfill_default_widgets) — generated via
`alembic revision --autogenerate` against a fresh empty database compared to
Base.metadata. Existing databases (which already have this schema, via that
hand-rolled path) are stamped at this revision rather than replayed through it;
see build_session_factory in app/db.py.

Revision ID: a4bb30b5eed6
Revises:
Create Date: 2026-09-13 07:56:10.977837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4bb30b5eed6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("max_agent_runs_per_hour", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tenant_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tenant_api_keys_tenant_id"),
        "tenant_api_keys",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("telegram_chat_id", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "widgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("allowed_origins", sa.JSON(), nullable=False),
        sa.Column("first_event_at", sa.DateTime(), nullable=True),
        sa.Column("feed_url", sa.String(length=500), nullable=True),
        sa.Column("feed_auth_token", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_widgets_tenant_id"), "widgets", ["tenant_id"], unique=False
    )
    op.create_table(
        "catalog_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("widget_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("story", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("price", sa.String(length=120), nullable=False),
        sa.Column("specs", sa.JSON(), nullable=False),
        sa.Column("use_case_tags", sa.JSON(), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("vector_synced", sa.Boolean(), nullable=False),
        sa.Column("ingestion_adapter", sa.String(length=20), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("sync_stale", sa.Boolean(), nullable=False),
        sa.Column("ingestion_meta", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["widget_id"],
            ["widgets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_items_tenant_id"), "catalog_items", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_items_widget_id"), "catalog_items", ["widget_id"], unique=False
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("widget_id", sa.Integer(), nullable=True),
        sa.Column("visitor_id", sa.String(length=64), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("catalog_item_ids", sa.JSON(), nullable=False),
        sa.Column("retrieval_meta", sa.JSON(), nullable=False),
        sa.Column("behavior_summary", sa.Text(), nullable=False),
        sa.Column("activity_hash", sa.String(length=64), nullable=False),
        sa.Column("trigger_reason", sa.String(length=120), nullable=False),
        sa.Column("mesh_latency_ms", sa.Float(), nullable=True),
        sa.Column("mesh_prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("mesh_completion_tokens", sa.Integer(), nullable=True),
        sa.Column("mesh_cost_usd", sa.Float(), nullable=True),
        sa.Column("pushed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["widget_id"],
            ["widgets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_activity_hash"),
        "recommendations",
        ["activity_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_tenant_id"),
        "recommendations",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_visitor_id"),
        "recommendations",
        ["visitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_widget_id"),
        "recommendations",
        ["widget_id"],
        unique=False,
    )
    op.create_table(
        "widget_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("widget_id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["widget_id"],
            ["widgets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_widget_api_keys_widget_id"),
        "widget_api_keys",
        ["widget_id"],
        unique=False,
    )
    op.create_table(
        "widget_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("widget_id", sa.Integer(), nullable=True),
        sa.Column("visitor_id", sa.String(length=64), nullable=False),
        sa.Column("connection_id", sa.String(length=64), nullable=False),
        sa.Column(
            "opened_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["widget_id"],
            ["widgets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_widget_sessions_tenant_id"),
        "widget_sessions",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_widget_sessions_visitor_id"),
        "widget_sessions",
        ["visitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_widget_sessions_widget_id"),
        "widget_sessions",
        ["widget_id"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("widget_id", sa.Integer(), nullable=True),
        sa.Column("visitor_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("catalog_item_id", sa.Integer(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"],
            ["catalog_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["widget_id"],
            ["widgets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_tenant_id"), "events", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_events_visitor_id"), "events", ["visitor_id"], unique=False
    )
    op.create_index(op.f("ix_events_widget_id"), "events", ["widget_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_widget_id"), table_name="events")
    op.drop_index(op.f("ix_events_visitor_id"), table_name="events")
    op.drop_index(op.f("ix_events_tenant_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_widget_sessions_widget_id"), table_name="widget_sessions")
    op.drop_index(op.f("ix_widget_sessions_visitor_id"), table_name="widget_sessions")
    op.drop_index(op.f("ix_widget_sessions_tenant_id"), table_name="widget_sessions")
    op.drop_table("widget_sessions")
    op.drop_index(op.f("ix_widget_api_keys_widget_id"), table_name="widget_api_keys")
    op.drop_table("widget_api_keys")
    op.drop_index(op.f("ix_recommendations_widget_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_visitor_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_tenant_id"), table_name="recommendations")
    op.drop_index(
        op.f("ix_recommendations_activity_hash"), table_name="recommendations"
    )
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_catalog_items_widget_id"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_tenant_id"), table_name="catalog_items")
    op.drop_table("catalog_items")
    op.drop_index(op.f("ix_widgets_tenant_id"), table_name="widgets")
    op.drop_table("widgets")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tenant_api_keys_tenant_id"), table_name="tenant_api_keys")
    op.drop_table("tenant_api_keys")
    op.drop_table("tenants")
    # ### end Alembic commands ###
